apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: thrall
  name: thrall-claim
spec:
  storageClassName: thrall-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi