apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
    app: thrall
  name: thrall-volume
spec:
  storageClassName: thrall-data
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/chain/thrall"