apiVersion: v1
kind: Service
metadata:
  labels:
    app: thrall
  name: thrall
spec:
  ports:
  - name: "p2p"
    port: 9933
  - name: "9944"
    port: 9944
    targetPort: 9944
  - name: "30333"
    port: 30333
    targetPort: 30333
  selector:
    app: thrall
