version: '3.7'

services:
  alice:
    image: panlog/panlog-node:latest
    container_name: alice
    restart: always
    volumes:
      - ./data/chain/alice:/data
    ports:
      - 9944:9944
      - 30333:30333
    networks:
      - panlog
    depends_on:
      - telemetry-backend
    command: >
             --base-path /data
             --chain local
             --alice
             --port 30333
             --ws-port 9944
             --rpc-port 9933
             --unsafe-rpc-external
             --unsafe-ws-external
             --rpc-cors all
             --validator
             --telemetry-url 'ws://telemetry-backend:8000/submit 0'
             --prometheus-external

  bob:
    image: panlog/panlog-node:latest
    container_name: bob
    restart: always
    volumes:
      - ./data/chain/bob:/data
    ports:
      - 9943:9944
    networks:
      - panlog
    depends_on:
      - telemetry-backend
      - alice  
    command: >
             --base-path /data
             --chain local
             --bob
             --port 30333
             --ws-port 9944
             --rpc-port 9933
             --unsafe-rpc-external
             --unsafe-ws-external
             --validator
             --rpc-cors all
             --telemetry-url 'ws://telemetry-backend:8000/submit 0'
             --bootnodes /ip4/127.0.0.1/tcp/30333/p2p/QmZDaPqukwyMEL611soGCvxNR6qikkrdfwFZe57BgVNW3v
             --prometheus-external

  charlie:
    image: panlog/panlog-node:latest
    container_name: charlie
    restart: always
    volumes:
      - ./data/chain/charlie:/data
    ports:
      - 9945:9944
    networks:
      - panlog
    depends_on:
      - telemetry-backend
      - alice  
    command: >
             --base-path /data
             --chain local
             --charlie
             --port 30333
             --ws-port 9944
             --rpc-port 9933
             --unsafe-rpc-external
             --unsafe-ws-external
             --rpc-cors all
             --telemetry-url 'ws://telemetry-backend:8000/submit 0'
             --bootnodes /ip4/127.0.0.1/tcp/30333/p2p/QmZDaPqukwyMEL611soGCvxNR6qikkrdfwFZe57BgVNW3v
             --prometheus-external

  panlog-ui:
    image: panlog/panlog-ui:latest
    container_name: panlog-ui
    restart: always
    ports:
      - 80:80
    networks:
      - panlog

  telemetry-backend:
    image: panlog/telemetry-backend:latest
    container_name: telemetry-backend
    restart: always
    environment:
      - PORT=8000
    ports:
      - 8000:8000
    networks:
      - panlog
    command: >
      -l 0.0.0.0:8000

  
  telemetry-frontend:
    image: panlog/telemetry-frontend:latest
    container_name: telemetry-frontend
    restart: always
    environment:
      - SUBSTRATE_TELEMETRY_URL=ws://localhost:8000/feed
    depends_on:
      - telemetry-backend
    ports:
      - 8080:80
    networks:
      - panlog

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    depends_on:
      - cadvisor
      - alice
      - charlie
      - bob  
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus/
      - ./data/monitoring/prometheus:/prometheus  
    networks:
      - panlog
    command: >
              --config.file=/etc/prometheus/prometheus.yml
              --storage.tsdb.path=/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3001:3000
    user: "104"
    depends_on:
      - prometheus
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./data/monitoring/graphana:/var/lib/grafana  
    networks:
      - panlog

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    restart: always
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro    
    networks:
      - panlog

  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - panlog
        
networks:
  panlog:
