global:
  scrape_interval: 5s

scrape_configs:
  # prometheus self monitoring
  - job_name: 'prometheus'
    static_configs:
         - targets: ['localhost:9090']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
        
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
           
  - job_name: 'substrate-nodes'
    static_configs:
      - targets: ['alice:9615']
        labels:
          network: testnet
      - targets: ['bob:9615']
        labels:
          network: testnet
      - targets: ['charlie:9615']
        labels:
          network: testnet
