apiVersion: v1
kind: Service
metadata:
  labels:
    app: telemetry-backend
  name: telemetry-backend
spec:
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8080
  selector:
    app: telemetry-backend