version: '3.7'

services:
  # root-validator node
  thrall:
    image: andskur/substrate:latest
    container_name: thrall
    restart: always
    volumes:
      - ./data/chain/thrall:/data
      - ./keys/thrall:/keys
      - ./chainSpec:/chainSpec
      - ./scripts:/scripts  
    ports:
      - 9933:9933
      - 9944:9944
      - 30333:30333
    networks:
      - panlog
    depends_on:
      - telemetry-backend
    command: >
             --name thrall
             --base-path /data
             --chain /chainSpec/composeLocalSpecRaw.json
             --node-key-file /keys/node.key
             --port 30333
             --ws-port 9944
             --rpc-port 9933
             --unsafe-rpc-external
             --unsafe-ws-external
             --rpc-cors all
             --validator
             --prometheus-external

  # validator node
  jaina:
    image: andskur/substrate:latest
    container_name: jaina
    restart: always
    volumes:
      - ./data/chain/jaina:/data
      - ./keys/jaina:/keys
      - ./chainSpec:/chainSpec
      - ./scripts:/scripts  
    ports:
      - 9934:9933
      - 9945:9944
      - 30334:30333
    networks:
      - panlog
    depends_on:
      - telemetry-backend
      - thrall  
    command: >
             --name jaina
             --base-path /data
             --chain /chainSpec/composeLocalSpecRaw.json
             --node-key-file /keys/node.key
             --port 30333
             --ws-port 9944
             --rpc-port 9933
             --unsafe-rpc-external
             --unsafe-ws-external
             --rpc-cors all
             --validator
             --prometheus-external

  # no validator node
  kairn:
    image: andskur/substrate:latest
    container_name: kairn
    restart: always
    volumes:
      - ./data/chain/kairn:/data
      - ./chainSpec:/chainSpec
    ports:
      - 9946:9944
    networks:
      - panlog
    depends_on:
      - telemetry-backend
      - thrall  
    command: >
             --name kairn
             --base-path /data
             --chain /chainSpec/composeLocalSpecRaw.json
             --port 30333
             --ws-port 9944
             --rpc-port 9933
             --rpc-external
             --ws-external
             --rpc-cors all
             --prometheus-external

  ## frontend application
  ui-app:
    image: andskur/substrate-ui:latest
    container_name: ui-app
    restart: always
    ports:
      - 80:80
    networks:
      - panlog

  telemetry-backend:
    image: andskur/telemetry-backend:latest
    container_name: telemetry-backend
    restart: always
    environment:
      - PORT=8000
    ports:
      - 8000:8000
    networks:
      - panlog
    command: >
      -l 0.0.0.0:8000

  
  telemetry-frontend:
    image: andskur/telemetry-frontend:latest
    container_name: telemetry-frontend
    restart: always
    environment:
      - SUBSTRATE_TELEMETRY_URL=ws://localhost:8000/feed
    depends_on:
      - telemetry-backend
    ports:
      - 8080:80
    networks:
      - panlog

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    depends_on:
      - cadvisor
      - thrall
      - jaina
      - kairn  
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus/
      - ./data/monitoring/prometheus:/prometheus  
    networks:
      - panlog
    command: >
              --config.file=/etc/prometheus/prometheus.yml
              --storage.tsdb.path=/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - 3001:3000
    user: "104"
    depends_on:
      - prometheus
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./data/monitoring/graphana:/var/lib/grafana  
    networks:
      - panlog

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    restart: always
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro    
    networks:
      - panlog

  cadvisor:
    image: google/cadvisor
    container_name: cadvisor
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - panlog
        
networks:
  panlog:

