apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: jaina
  name: jaina-claim
spec:
  storageClassName: jaina-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi