apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
    app: jaina
  name: jaina-volume
spec:
  storageClassName: jaina-data
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/chain/jaina"