global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - /etc/prometheus/prometheus.rules

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
          - "alertmanager.monitoring.svc:9093"

scrape_configs:
  # substrate metrics
  - job_name: 'substrate-nodes'
    static_configs:
      - targets: ['thrall:9615']
        labels:
          network: local
      - targets: ['jaina:9615']
        labels:
          network: local
      - targets: ['kairn:9615']
        labels:
          network: local