apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: {{ .Values.app }}
  name: {{ .Values.app }}-activate
  annotations:
    "helm.sh/hook": post-install
#    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
        - name: {{ .Values.app }}-activation-job
          image: curlimages/curl
          imagePullPolicy: "IfNotPresent"
          envFrom:
            - secretRef:
                name: {{ .Values.app }}-keys
          volumeMounts:
            - name: import-script
              mountPath: /scripts
          command:
            - /bin/sh
            - -c
            - |
              cp /scripts/import_keys /tmp/import_keys
              cd /tmp
              chmod +x import_keys
              sh import_keys http://{{ .Values.app }}:9933
      volumes:
        - name: import-script
          configMap:
            name: {{ .Release.Name }}-importscript
            items:
              - key: import_keys.sh
                path: import_keys
      restartPolicy: Never

