apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: {{ .Values.app }}
  name: {{ .Values.app }}-claim
spec:
  storageClassName: {{ .Values.app }}-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi