apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.app }}-keys
data:
  KEY_P2P: {{ .Values.validator.p2p }}
  KEY_MNEMONIC: {{ .Values.validator.mnemonic }}
  KEY_SR25519: {{ .Values.validator.sr25519 }}
  KEY_ED25519: {{ .Values.validator.ed25519 }}
