apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.app }}
  name: {{ .Values.app }}
spec:
  ports:
  - name: "rpc"
    port: 9933
    targetPort: 9933
  - name: "ws"
    port: 9944
    targetPort: 9944
  - name: "p2p"
    port: 30333
    targetPort: 30333
  selector:
    app: {{ .Values.app }}
